updated java download script to work with the new oracle download requirements
sonofagl1tch/AWSDetonationLab pull request #43
Opened 2018-11-02 01:36 UTC by sonofagl1tch

updated java download script to work with the new Oracle download requirements

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2018-11-18 02:26 UTC, mgmacias95 commented on additionalInstallationScripts/installWazuh.sh
> +#curl -Lo jre-8-linux-x64.rpm --header "Cookie: oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jre-8u181-linux-x64.
Remove this comment. We use GitHub to be able to go back to previous changes in case it's necessary, there's no need to actually save old changes in code comments 😉.

2018-11-18 02:26 UTC, mgmacias95 requested changes
Remove comments

2018-11-19 15:10 UTC, sonofagl1tch commented on additionalInstallationScripts/installWazuh.sh
> +#curl -Lo jre-8-linux-x64.rpm --header "Cookie: oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jre-8u181-linux-x64.
changes completed

2018-11-25 20:04 UTC, mgmacias95 approved these changes
Java is correctly downloaded.

2018-11-25 20:05 UTC, merged